version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    environment:
      HOST: 0.0.0.0
    ports:
      - "8080:8080"
      - "3000:3000"